version: '3.2'
services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      server:
        condition: service_started
        restart: true
    networks:
      - my_network
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
      - my_network
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=twitter
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d twitter -U admin"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - '5432:5432'
    networks:
      - my_network
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./db/:/var/lib/postgresql/data
  db_test:
    image: postgres:latest
    environment:
      - POSTGRES_DB=twitter_test
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d twitter_test -U admin" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - '5433:5432'
    networks:
      - my_network
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh


networks:
  my_network:
    driver: bridge
