set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    SELECT 'CREATE DATABASE $POSTGRES_DB' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$POSTGRES_DB');
    SELECT 'CREATE USER $POSTGRES_USER WITH ENCRYPTED PASSWORD $POSTGRES_PASSWORD; GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_USER TO $POSTGRES_DB;' WHERE NOT EXISTS (SELECT FROM pg_roles  WHERE  rolname = '$POSTGRES_USER');
EOSQL